title: Dashboard

views:
  - !include views/summary.yaml
  - !include views/lights.yaml
  - !include views/energy.yaml
  - !include views/environment.yaml
  - !include views/network.yaml
  - !include views/devices.yaml

decluttering_templates: !include templates/decluttering-card.yaml
button_card_templates: !include_dir_merge_named templates/button-card/
apexcharts_card_templates: !include templates/apexcharts_card_templates.yaml

background: >-
  linear-gradient(to bottom, rgba(var(--rgb-primary-color),.2),
  var(--primary-background-color))