- platform: group
  name: PC Corner
  unique_id: pc_corner
  entities:
    - light.pccorner1
    - light.pccorner2
    - light.pccorner3

- platform: group
  name: Living Room
  unique_id: lights_living_room
  entities:
    - light.pc_corner
    - light.dinner_corner
    - light.play_corner
    - light.tv_corner

- platform: group
  name: Toilet Upstairs
  unique_id: lights_toilet_upstairs
  entities:
    - light.toilet_first_floor_1
    - light.toilet_first_floor_2

- platform: group
  name: Garage
  unique_id: lights_garage
  entities:
    - light.garage_front_light
    - light.garage_back_light

- platform: group
  name: All Lights
  unique_id: all_lights
  entities:
    # Ground Floor
    - light.hallway_light_0
    - light.pc_corner
    - light.dinner_corner
    - light.play_corner
    - light.tv_corner
    - light.kitchen
    - light.toilet_downstairs
    # First Floor
    - light.bathroom_light
    - light.hallway_first_floor
    - light.bedroom_light
    - light.bed_side_lamp_tom
    - light.master_bedroom
    - light.toilet_upstairs
    # Second Floor
    - light.hobby_room
    - light.home_office
    # Outside
    - light.garage
    # Other
    - light.cupboard
