title: Environment
path: environment

type: custom:grid-layout
layout: !include view_layouts/view_base_layout.yaml
cards:
  - type: custom:layout-card
    layout_type: custom:grid-layout
    layout: !include view_layouts/view_column_layout.yaml
    view_layout:
      grid-area: cc
    cards:
      ############################################################
      # HEADER
      ############################################################
      - type: markdown
        view_layout:
          grid-column: 1/-1
        content: >
          # Environment
      ############################################################
      # HUMIDITY
      ############################################################
      - type: vertical-stack
        cards:
          - type: markdown
            content: Humidity
            view_layout:
              grid-column: 1/-1
          - type: vertical-stack
            in_card: true
            cards:
              - type: horizontal-stack
                cards:
                  - type: entity
                    entity: sensor.humidity
                    name: Outdoor
                    icon: none
                  - type: entity
                    entity: sensor.temperature_humidity_humidity
                    name: Indoor
                    icon: none
                  - type: entity
                    entity: sensor.indoor_outdoor_humidity_difference
                    name: Difference
              - type: custom:apexcharts-card
                config_templates:
                  - environment_chart
                series:
                  - entity: sensor.sun_solar_elevation
                    color: rgb(255,255,255)
                    opacity: .2
                    stroke_width: 1
                    yaxis_id: sun
                    unit: 째
                    show:
                      legend_value: false
                  - entity: sensor.sun_solar_elevation
                    color: rgb(255,255,255)
                    opacity: .2
                    stroke_width: 1
                    yaxis_id: sun
                    unit: 째
                    data_generator: |
                      const now = new Date();
                      const data = [[now.getTime() - 172800000, 0], [now.getTime(), 0], [now.getTime() + 86400000, 0]];
                      return data;
                  - entity: sensor.humidity
                    type: area
                    name: Buienradar
                    yaxis_id: main
                    stroke_width: .5
                    color: gray
                    opacity: .1
                    show:
                      datalabels: true
                      extremas: true
                  - entity: sensor.temperature_humidity_humidity
                    name: Living Room
                    stroke_width: .5
                    color: gray
                    yaxis_id: main
                    group_by:
                      func: first
                      duration: 30min
                    show:
                      datalabels: true
      ############################################################
      # TEMPERATURE
      ############################################################
      - type: vertical-stack
        cards:
          - type: markdown
            content: Temperature
            view_layout:
              grid-column: 1/-1
          - type: vertical-stack
            in_card: true
            cards:
              - type: horizontal-stack
                cards:
                  - type: entity
                    entity: sensor.feel_temperature
                    name: Outdoor
                    icon: none
                  - type: entity
                    entity: sensor.temperature_humidity_temperature
                    name: Indoor
                    icon: none
                  - type: entity
                    entity: sensor.indoor_outdoor_temperature_difference
                    name: Difference
              - type: custom:apexcharts-card
                config_templates:
                  - environment_chart
                series:
                  - entity: sensor.sun_solar_elevation
                    color: rgb(255,255,255)
                    opacity: .2
                    stroke_width: 1
                    yaxis_id: sun
                    unit: 째
                    show:
                      legend_value: false
                  - entity: sensor.sun_solar_elevation
                    color: rgb(255,255,255)
                    opacity: .2
                    stroke_width: 1
                    yaxis_id: sun
                    unit: 째
                    data_generator: |
                      const now = new Date();
                      const data = [[now.getTime() - 172800000, 0], [now.getTime(), 0], [now.getTime() + 86400000, 0]];
                      return data;
                  - entity: sensor.temperature
                    type: area
                    name: Buienradar
                    yaxis_id: main
                    stroke_width: .5
                    color: gray
                    opacity: .1
                    show:
                      datalabels: true
                      extremas: true
                  - entity: sensor.temperature_humidity_temperature
                    name: Living Room
                    stroke_width: .5
                    color: gray
                    yaxis_id: main
                    group_by:
                      func: first
                      duration: 30min
                    show:
                      datalabels: true