button_card_templates: !include_dir_merge_named templates/button-card/
decluttering_templates: !include templates/decluttering-card.yaml

views:
  - !include views/summary.yaml
  - !include views/lights.yaml
